ALTER TABLE url_mapping DROP CONSTRAINT IF EXISTS url_mapping_long_url_key;

ALTER TABLE url_mapping
    ALTER COLUMN slug TYPE VARCHAR(80),
    ADD COLUMN IF NOT EXISTS title VARCHAR(300),
    ADD COLUMN IF NOT EXISTS channel VARCHAR(80),
    ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

ALTER TABLE url_mapping
    ADD CONSTRAINT ck_url_mapping_status
        CHECK (status IN ('ACTIVE', 'PAUSED', 'EXPIRED', 'BLOCKED'));
